
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 22 17:49:18 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 25;
  public static final int DIVEQ = 31;
  public static final int GTEQUAL = 19;
  public static final int LBRACKET = 40;
  public static final int INCREMENT = 37;
  public static final int CHAR = 48;
  public static final int CONST = 42;
  public static final int MODEQ = 44;
  public static final int EQUALS = 36;
  public static final int SUBEQ = 32;
  public static final int NOTEQUAL = 18;
  public static final int LPAREN = 6;
  public static final int GREATER = 22;
  public static final int SEMI = 5;
  public static final int INTERFACE = 28;
  public static final int INT = 46;
  public static final int DECREMENT = 38;
  public static final int LESS = 21;
  public static final int MINUS = 24;
  public static final int RPAREN = 7;
  public static final int AND = 30;
  public static final int LEEQUAL = 20;
  public static final int OR = 29;
  public static final int BOOL = 47;
  public static final int COMMA = 8;
  public static final int CLASS = 27;
  public static final int PLUS = 11;
  public static final int MULTIPLY = 14;
  public static final int IF = 50;
  public static final int DOT = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 41;
  public static final int EQUAL = 17;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int NULL = 13;
  public static final int MOD = 23;
  public static final int IDENT = 49;
  public static final int VOID = 12;
  public static final int MULEQ = 34;
  public static final int ELSE = 51;
  public static final int LBRACE = 3;
  public static final int READ = 39;
  public static final int ENUM = 35;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int ADDEQ = 33;
  public static final int IMPLEMENTS = 26;
  public static final int SUB = 16;
  public static final int PRINT = 9;
}

