package rs.ac.bg.etf.pp1;

public class sym_old {
    public static final int ELSE = 17;
    public static final int IDENT = 15;
    public static final int PLUS = 11;
    public static final int RBRACE = 4;
    public static final int RPAREN = 7;
    public static final int EQUAL = 12;
    public static final int SEMI = 5;
    public static final int RETURN = 10;
    public static final int IF = 16;
    public static final int LPAREN = 6;
    public static final int LBRACE = 3;
    public static final int COMMA = 8;
    public static final int EOF = 0;
    public static final int NUMBER = 14;
    public static final int PROG = 2;
    public static final int PRINT = 9;
    public static final int error = 1;
    public static final int VOID = 13;
    public static final int MINUS = 18;
    public static final int MULTIPLY = 19;
    public static final int MOD = 20;
    public static final int DIVIDE = 21;
    public static final int INT = 22;
    public static final int CHAR = 23;
    public static final int BOOL = 24;
    public static final int AND = 25;
    public static final int OR = 26;
    public static final int INCREMENT = 27;
    public static final int DECREMENT = 28;
    public static final int GREATER = 29;
    public static final int NOTEQUAL = 30;
    public static final int LESS = 31;
    public static final int LEEQUAL = 32;
    public static final int GTEQUAL = 33;
    public static final int DOT = 34;
    public static final int NEW = 35;
    public static final int NULL = 36;
    public static final int READ = 37;
    public static final int CONST = 38;
    public static final int ENUM = 39;
    public static final int CLASS = 40;
    public static final int INTERFACE = 41;
    public static final int EXTENDS = 42;
    public static final int IMPLEMENTS = 43;
    public static final int LBRACKET = 44;
    public static final int RBRACKET = 45;
    public static final int EQUALS = 46;
    public static final int MULEQ = 47;
    public static final int MODEQ = 48;
    public static final int ADDEQ = 49;
    public static final int SUBEQ = 50;
    public static final int DIVEQ = 51;

}
